[toolchain]
anchor_version = "0.32.1"

[features]
seeds = true

[programs.localnet]
onchain_escrow = "E4Vq17qHGG1PFr5h6vZdQUb3nxhjJB9dwMijiVdxfZLd"

[programs.devnet]
onchain_escrow = "E4Vq17qHGG1PFr5h6vZdQUb3nxhjJB9dwMijiVdxfZLd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "/home/mbirochan/.config/solana/arthadev.json"

[scripts]
test = "anchor test"
