[toolchain]
anchor_version = "0.32.1"

[features]
seeds = true

[programs.localnet]
onchain_escrow = "HM1zYGd6WVH8e73U9QZW8spamWmLqzd391raEsfiNzEZ"

[programs.devnet]
onchain_escrow = "HM1zYGd6WVH8e73U9QZW8spamWmLqzd391raEsfiNzEZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Devnet"
wallet = "/home/mbirochan/.config/solana/arthadev.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
